version: '3.4'

services:
  customer-api:
    image: ${DOCKER_REGISTRY-}customer-api
    build:
      context: .
      dockerfile: Microservices/Poke.CloudSalesSystem.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SEQ_SERVER=seq
      - ConnectionStrings__Postgres=Host=customer-postgres;Port=5432;Database=customersDb;Username=guest;Password=guest
    ports:
      - 7001:80    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro   
   
  accounts-api:
    image: ${DOCKER_REGISTRY-}accounts-api
    build:
      context: .
      dockerfile: Microservices/Poke.CloudSalesSystem.Accounts/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SEQ_SERVER=seq
      - ConnectionStrings__Postgres=Host=accounts-postgres;Port=5432;Database=accountsDb;Username=guest;Password=guest
    ports:
      - 7002:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  licence-api:
    image: ${DOCKER_REGISTRY-}licence-api
    build:
      context: .
      dockerfile: Microservices/Poke.CloudSalesSystem.Licences/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SEQ_SERVER=seq
      - ConnectionStrings__Postgres=Host=licences-postgres;Port=5432;Database=licencesDb;Username=guest;Password=guest
    ports:
      - 7003:80    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro  
      
  product-api:
    image: ${DOCKER_REGISTRY-}product-api
    build:
      context: .
      dockerfile: Microservices/Poke.CloudSalesSystem.Products/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SEQ_SERVER=seq
    ports:
      - 7004:80    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro   
      
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8089:80
    volumes:
      - ./.containers/seq:/data
      
##### DATABASE #####
  customer-postgres:
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: customersDb
    ports:
      - 6432:5432  
    volumes:
      - postgres-customer-data:/var/lib/postgresql/data 
  accounts-postgres:
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: accountsDb
    ports:
      - 7432:5432  
    volumes:
      - postgres-accounts-data:/var/lib/postgresql/data 
  licences-postgres:
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: licencesDb
    ports:
      - 8432:5432  
    volumes:
      - postgres-licences-data:/var/lib/postgresql/data 
      

volumes:
  postgres-customer-data:
  postgres-accounts-data:
  postgres-licences-data: