version: '3.4'

services:
  customer-api:
    image: ${DOCKER_REGISTRY-}customer-api
    build:
      context: .
      dockerfile: Microservices/Poke.CloudSalesSystem.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SEQ_SERVER=seq
      - ConnectionStrings__Postgres=Host=customer-postgres;Port=5432;Database=customersDb;Username=guest;Password=guest
    depends_on:
      - customer-postgres
    ports:
      - 7001:80    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro   
      
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8089:80
    volumes:
      - ./.containers/seq:/data
      
  customer-postgres:
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: customersDb
    ports:
      - 6432:5432  
    volumes:
      - postgres-customer-data:/var/lib/postgresql/data 
      

volumes:
  postgres-customer-data: